// @generated by scripts/sync-observation.mjs from packages/ui-bridge/src/observation/observation.ts — do not edit.
// Edit the canonical file, then run `npm run observation:sync`; CI runs
// `npm run observation:check` and fails on any drift.

/**
 * Observation envelope — the shape every UI Bridge observation surface answers
 * in: WHAT was seen (`measured`), that nothing was there (`absent`), or that the
 * producer could not look (`unknown`) — and, in every case, where the answer
 * came from (`provenance`).
 *
 * Why it exists: an empty findings list used to mean either "the page has
 * nothing there" or "the producer never looked", byte-identically, and only the
 * first is a statement about the page. `page-health` rendered a missing
 * `elements` key as a CRITICAL blank page; an agent reading that went looking
 * for a bug no evidence pointed at.
 *
 * This is the TypeScript twin of the canonical Rust type
 * `qontinui-schemas/rust-vision-core/src/observation.rs`. `@qontinui/ui-bridge`
 * is a standalone package and takes no dependency on qontinui-schemas; it is
 * held to the Rust canon by SDK-captured fixtures the schemas crate parses
 * strictly (plan 2026-09-20-ui-bridge-observations-…, D2). The two MUST stay
 * structurally identical on the wire:
 *
 * ```jsonc
 * {
 *   "status": "measured" | "absent" | "unknown",       // always present
 *   "value": <T>,                                       // present iff measured
 *   "unknown": { "code": <UnknownCode>, "detail": "…" }, // present iff unknown
 *   "provenance": {                                     // always present, EVERY key always present
 *     "producer": { "id": "…", "version": "…" },
 *     "observedAt": "<RFC3339>" | null,
 *     "evaluatedAt": "<RFC3339>",
 *     "coverage": { "considered": n, "measured": n,
 *                   "unmeasured": [{ "dimension": "…", "count": n, "code": <UnknownCode> }] },
 *     "confidence": <0..1> | null,
 *     "cache": { "hit": bool, "storedAt": "<RFC3339>" | null, "keyInputs": ["…"] } | null,
 *     "source": { … } | null
 *   }
 * }
 * ```
 *
 * `null` in `provenance` is a STATEMENT, never an omission: `confidence: null`
 * says "a deduction, not an estimate", `cache: null` says "this producer has no
 * cache", `observedAt: null` says "no sample was taken". A key is therefore
 * never left out, and the constructors below are the only way to build one.
 *
 * The envelope adds no score and no verdict — `healthy`/`unhealthy` never
 * appears in it.
 */

// ============================================================================
// Unknown codes
// ============================================================================

/**
 * Why a producer could not answer. A CLOSED set: every `unknown` observation
 * carries exactly one of these, so an agent branches on the code rather than
 * parsing English out of `detail`.
 */
export type UnknownCode =
  /** The bridge/app could not be reached. */
  | 'app_unreachable'
  /** The running build does not serve this capability (e.g. an SDK route that needs a runner). */
  | 'capability_unavailable_in_build'
  /** The producer ran and errored (transport, HTTP status, timeout, thrown exception). */
  | 'producer_failed'
  /** The producer did not run — e.g. zero registered components, nothing to look at yet. */
  | 'producer_not_run'
  /** A required input was absent (no `elements` key, no bbox, no frame). */
  | 'input_missing'
  /** Observations existed but all fell under the caller's confidence floor. */
  | 'below_confidence_floor'
  /** A model reply could not be parsed/validated. */
  | 'model_reply_unparseable'
  /** The question needs more than one frame (e.g. `animation_settled`). */
  | 'needs_multi_frame_input'
  /** The input is known to be stale. */
  | 'stale_input';

/** Every {@link UnknownCode}, in the canonical (wire-contract) order. */
export const UNKNOWN_CODES: readonly UnknownCode[] = [
  'app_unreachable',
  'capability_unavailable_in_build',
  'producer_failed',
  'producer_not_run',
  'input_missing',
  'below_confidence_floor',
  'model_reply_unparseable',
  'needs_multi_frame_input',
  'stale_input',
] as const;

/** Type guard: is `value` one of the closed {@link UnknownCode} members? */
export function isUnknownCode(value: unknown): value is UnknownCode {
  return typeof value === 'string' && (UNKNOWN_CODES as readonly string[]).includes(value);
}

// ============================================================================
// Provenance
// ============================================================================

/** Which producer answered, and at what version. */
export interface ObservationProducer {
  /** e.g. `sdk/page-health`, `runner/vision-extract`, `vision-core/layout`. */
  id: string;
  /** The producing package's or crate's version. */
  version: string;
}

/** One dimension the producer could NOT measure, how many items it affected, and why. */
export interface UnmeasuredDimension {
  /** What went unmeasured, e.g. `geometry`, `text`. */
  dimension: string;
  /** How many considered items lacked it. */
  count: number;
  code: UnknownCode;
}

/**
 * How much of what the producer looked at it could actually measure. A
 * non-empty `unmeasured` makes a `measured` observation DEGRADED (legal) and an
 * `absent` one ILLEGAL.
 */
export interface ObservationCoverage {
  /** Items the producer considered. */
  considered: number;
  /** Items it could measure in full. */
  measured: number;
  /** Named dimensions it could not measure. Always present — `[]` is the statement "full coverage". */
  unmeasured: UnmeasuredDimension[];
}

/** Provenance of a cached answer. Every key always present. */
export interface ObservationCache {
  /** Whether this answer was served from the cache. */
  hit: boolean;
  /** When the served entry was stored. `null` on a miss or when the cache keeps no timestamp. */
  storedAt: string | null;
  /** The inputs the cache key was derived from, so a reader can judge what a hit is keyed on. */
  keyInputs: string[];
}

/** Where an {@link Observation} came from. EVERY key is always present. */
export interface ObservationProvenance {
  producer: ObservationProducer;
  /** When the underlying state was sampled (snapshot time / frame capture). `null` = no sample was taken. */
  observedAt: string | null;
  /** When the producer ran. Never null. */
  evaluatedAt: string;
  coverage: ObservationCoverage;
  /** Finite, in `[0, 1]`, or `null` = "a deduction, not an estimate". */
  confidence: number | null;
  /** `null` = this producer has no cache. */
  cache: ObservationCache | null;
  /** Source attribution as a JSON object, or `null` = the producer has none to give. */
  source: Record<string, unknown> | null;
}

/** Why a producer could not answer. */
export interface ObservationUnknown {
  code: UnknownCode;
  /** Human prose. Never the only carrier of the reason — `code` is. */
  detail: string;
}

/** The three answers, as the `status` tag spells them on the wire. */
export type ObservationStatus = 'measured' | 'absent' | 'unknown';

/** The producer looked and saw `value`. */
export interface MeasuredObservation<T> {
  status: 'measured';
  value: T;
  provenance: ObservationProvenance;
}

/** The producer looked with FULL coverage and found nothing. */
export interface AbsentObservation {
  status: 'absent';
  provenance: ObservationProvenance;
}

/** The producer could not look. Carries no `value`. */
export interface UnknownObservation {
  status: 'unknown';
  unknown: ObservationUnknown;
  provenance: ObservationProvenance;
}

/**
 * The envelope. A discriminated union on `status`, so there is no `measured`
 * without a `value`, no `unknown` without a `code`, and no `value` beside an
 * `absent` — at compile time. The one invariant spanning the state AND the
 * provenance (`absent` only over full coverage) is enforced by
 * {@link Observation.absent}.
 */
export type Observation<T> = MeasuredObservation<T> | AbsentObservation | UnknownObservation;

// ============================================================================
// Constructors
// ============================================================================

/** Thrown when a constructor is asked for an illegal envelope. */
export class ObservationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ObservationError';
  }
}

/** A timestamp in any of the forms producers hold one in. */
export type ObservationTime = string | number | Date;

function toRfc3339(t: ObservationTime): string {
  const d = t instanceof Date ? t : new Date(t);
  if (Number.isNaN(d.getTime())) {
    throw new ObservationError(`not a valid timestamp: ${String(t)}`);
  }
  return d.toISOString();
}

/** Non-finite → `null` (a statement, not a number); finite → clamped to `[0, 1]`. Mirrors the Rust canon. */
function normalizeConfidence(c: number | null | undefined): number | null {
  if (c === null || c === undefined || !Number.isFinite(c)) return null;
  return Math.min(1, Math.max(0, c));
}

/** Inputs for {@link Observation.provenance}. Omitted optional keys become the explicit `null` statements. */
export interface ObservationProvenanceInit {
  producer: ObservationProducer;
  /** When the underlying state was sampled. Omitted / `null` = no sample was taken. */
  observedAt?: ObservationTime | null;
  /** When the producer ran. Defaults to now. */
  evaluatedAt?: ObservationTime;
  /** Defaults to `{ considered: 0, measured: 0, unmeasured: [] }`. */
  coverage?: ObservationCoverage;
  /** Omitted / `null` / non-finite = a deduction, not an estimate. */
  confidence?: number | null;
  /** Omitted / `null` = this producer has no cache. */
  cache?: { hit: boolean; storedAt: ObservationTime | null; keyInputs: string[] } | null;
  /** Omitted / `null` = no source attribution. */
  source?: Record<string, unknown> | null;
}

/** Full coverage of `n` considered items. */
function fullCoverage(n: number): ObservationCoverage {
  return { considered: n, measured: n, unmeasured: [] };
}

/** A count on the wire is a `u64` in the Rust canon: a non-negative safe integer. */
function assertCount(value: unknown, what: string): asserts value is number {
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) {
    throw new ObservationError(`${what} must be a non-negative integer, got ${String(value)}`);
  }
}

function assertCoverage(coverage: ObservationCoverage): void {
  if (!coverage || typeof coverage !== 'object') {
    throw new ObservationError('coverage must be an object');
  }
  assertCount(coverage.considered, 'coverage.considered');
  assertCount(coverage.measured, 'coverage.measured');
  if (!Array.isArray(coverage.unmeasured)) {
    throw new ObservationError('coverage.unmeasured must be an array');
  }
  coverage.unmeasured.forEach((u, i) => {
    if (!u || typeof u.dimension !== 'string') {
      throw new ObservationError(`coverage.unmeasured[${i}].dimension must be a string`);
    }
    assertCount(u.count, `coverage.unmeasured[${i}].count`);
    if (!isUnknownCode(u.code)) {
      throw new ObservationError(
        `coverage.unmeasured[${i}].code is not an UnknownCode: ${String(u.code)}`
      );
    }
  });
}

/** `source` is a JSON object or `null` — never an array, a primitive, or `undefined`. */
function assertSource(source: unknown): asserts source is Record<string, unknown> | null {
  if (source === null) return;
  if (typeof source !== 'object' || Array.isArray(source)) {
    throw new ObservationError('source must be a JSON object or null');
  }
}

/**
 * RFC3339 date-time as chrono's `DateTime<Utc>` deserializer accepts it:
 * full date, `T` (or `t`/space), full time with optional fraction, and a `Z`
 * or `±HH:MM` offset — plus a calendar-valid instant.
 */
const RFC3339 = /^\d{4}-\d{2}-\d{2}[Tt ]\d{2}:\d{2}:\d{2}(\.\d+)?([Zz]|[+-]\d{2}:\d{2})$/;

function isRfc3339(value: unknown): value is string {
  return typeof value === 'string' && RFC3339.test(value) && !Number.isNaN(Date.parse(value));
}

/**
 * Re-check a provenance block the constructors are handed — it may have been
 * built by hand rather than by {@link Observation.provenance}.
 */
function assertProvenance(prov: ObservationProvenance): void {
  if (!prov || typeof prov !== 'object') throw new ObservationError('provenance is required');
  if (
    !prov.producer ||
    typeof prov.producer.id !== 'string' ||
    typeof prov.producer.version !== 'string'
  ) {
    throw new ObservationError('producer must carry a string id and version');
  }
  if (!isRfc3339(prov.evaluatedAt)) {
    throw new ObservationError(
      `evaluatedAt must be an RFC3339 date-time, got ${String(prov.evaluatedAt)}`
    );
  }
  if (prov.observedAt !== null && !isRfc3339(prov.observedAt)) {
    throw new ObservationError(
      `observedAt must be an RFC3339 date-time or null, got ${String(prov.observedAt)}`
    );
  }
  assertCoverage(prov.coverage);
  if (
    prov.confidence !== null &&
    (typeof prov.confidence !== 'number' ||
      !Number.isFinite(prov.confidence) ||
      prov.confidence < 0 ||
      prov.confidence > 1)
  ) {
    throw new ObservationError(
      `confidence must be in [0, 1] or null, got ${String(prov.confidence)}`
    );
  }
  if (prov.cache !== null) {
    if (
      typeof prov.cache !== 'object' ||
      typeof prov.cache.hit !== 'boolean' ||
      !Array.isArray(prov.cache.keyInputs) ||
      !prov.cache.keyInputs.every((k) => typeof k === 'string')
    ) {
      throw new ObservationError(
        'cache must be { hit: boolean, storedAt, keyInputs: string[] } or null'
      );
    }
    if (prov.cache.storedAt !== null && !isRfc3339(prov.cache.storedAt)) {
      throw new ObservationError(
        `cache.storedAt must be an RFC3339 date-time or null, got ${String(prov.cache.storedAt)}`
      );
    }
  }
  assertSource(prov.source);
}

function provenance(init: ObservationProvenanceInit): ObservationProvenance {
  if (
    !init.producer ||
    typeof init.producer.id !== 'string' ||
    typeof init.producer.version !== 'string'
  ) {
    throw new ObservationError('producer must carry a string id and version');
  }
  const coverage = init.coverage ?? fullCoverage(0);
  assertCoverage(coverage);
  const source = init.source ?? null;
  assertSource(source);
  const built: ObservationProvenance = {
    producer: { id: init.producer.id, version: init.producer.version },
    observedAt:
      init.observedAt === undefined || init.observedAt === null ? null : toRfc3339(init.observedAt),
    evaluatedAt: toRfc3339(init.evaluatedAt ?? new Date()),
    coverage: {
      considered: coverage.considered,
      measured: coverage.measured,
      unmeasured: coverage.unmeasured.map((u) => ({
        dimension: u.dimension,
        count: u.count,
        code: u.code,
      })),
    },
    confidence: normalizeConfidence(init.confidence),
    cache: init.cache
      ? {
          hit: init.cache.hit,
          storedAt: init.cache.storedAt === null ? null : toRfc3339(init.cache.storedAt),
          keyInputs: [...init.cache.keyInputs],
        }
      : null,
    source,
  };
  assertProvenance(built);
  return built;
}

/**
 * The producer looked and saw `value`. THROWS {@link ObservationError} on
 * `undefined`: a measured observation whose `value` key would vanish from
 * the wire is exactly the missing-key shape the Rust canon refuses.
 */
function measured<T>(value: T, prov: ObservationProvenance): Observation<T> {
  if (value === undefined) {
    throw new ObservationError(
      'measured requires a value; report "nothing there" as absent and "could not look" as unknown'
    );
  }
  assertProvenance(prov);
  return { status: 'measured', value, provenance: prov };
}

/**
 * The producer looked and found nothing. THROWS {@link ObservationError} when
 * `coverage.unmeasured` is non-empty: "absent" can never be asserted over a
 * region the producer did not measure.
 */
function absent<T = never>(prov: ObservationProvenance): Observation<T> {
  assertProvenance(prov);
  if (prov.coverage.unmeasured.length > 0) {
    const dims = prov.coverage.unmeasured
      .map((u) => `${u.dimension} x${u.count} (${u.code})`)
      .join(', ');
    throw new ObservationError(
      `cannot assert absent over unmeasured coverage: ${dims}. ` +
        'Report the observation as measured (degraded) or unknown instead.'
    );
  }
  return { status: 'absent', provenance: prov };
}

function unknown<T = never>(
  code: UnknownCode,
  detail: string,
  prov: ObservationProvenance
): Observation<T> {
  if (!isUnknownCode(code)) {
    throw new ObservationError(`not an UnknownCode: ${String(code)}`);
  }
  if (typeof detail !== 'string') {
    throw new ObservationError('unknown requires a string detail');
  }
  assertProvenance(prov);
  return { status: 'unknown', unknown: { code, detail }, provenance: prov };
}

/**
 * Constructors for the envelope. `Observation.measured` / `.absent` /
 * `.unknown` are the ONLY way to build one; `.provenance` builds the block
 * with every nullable key stated explicitly.
 *
 * @example
 * ```ts
 * // `Observation` is exported by the package that ships this module.
 * const prov = Observation.provenance({
 *   producer: { id: 'sdk/page-health', version: '0.28.0' },
 *   observedAt: Date.now(),
 * });
 * const obs = Observation.unknown('input_missing', 'no elements key', prov);
 * ```
 */
export const Observation = {
  provenance,
  fullCoverage,
  measured,
  absent,
  unknown,
} as const;
