# @generated from diagnostics/codes.json — do not edit
"""Canonical UI Bridge diagnostic code vocabulary + recovery catalog.

Source of truth: ``ui-bridge/diagnostics/codes.json``. Regenerated by
``ui-bridge/scripts/gen-diagnostics.ts``. Do not edit by hand.
"""

from __future__ import annotations

from enum import Enum
from typing import Any


class UiBridgeErrorCode(str, Enum):
    """Every canonical ``UB-`` diagnostic code."""

    ACTION_FAILED = "UB-ACTION-FAILED"
    ACTION_REJECTED = "UB-ACTION-REJECTED"
    ACTION_TIMEOUT = "UB-ACTION-TIMEOUT"
    AMBIGUOUS_MATCH = "UB-AMBIGUOUS-MATCH"
    ASSERT_CONTRAST = "UB-ASSERT-CONTRAST"
    ASSERT_ELEMENT_MISSING = "UB-ASSERT-ELEMENT-MISSING"
    ASSERT_LAYOUT = "UB-ASSERT-LAYOUT"
    ASSERT_TEXT_MISMATCH = "UB-ASSERT-TEXT-MISMATCH"
    ASSERT_TIMEOUT = "UB-ASSERT-TIMEOUT"
    ASSERT_VISIBILITY = "UB-ASSERT-VISIBILITY"
    ELEM_BLOCKED = "UB-ELEM-BLOCKED"
    ELEM_DISABLED = "UB-ELEM-DISABLED"
    ELEM_NOT_ENABLED = "UB-ELEM-NOT-ENABLED"
    ELEM_NOT_FOUND = "UB-ELEM-NOT-FOUND"
    ELEM_NOT_INTERACTABLE = "UB-ELEM-NOT-INTERACTABLE"
    ELEM_NOT_VISIBLE = "UB-ELEM-NOT-VISIBLE"
    HEALTH_EMPTY_CONTENT_AREA = "UB-HEALTH-EMPTY-CONTENT-AREA"
    HEALTH_EMPTY_TEXT_SIGNAL = "UB-HEALTH-EMPTY-TEXT-SIGNAL"
    HEALTH_ERROR_TEXT_SIGNAL = "UB-HEALTH-ERROR-TEXT-SIGNAL"
    HEALTH_LOADING_CLASS_SIGNAL = "UB-HEALTH-LOADING-CLASS-SIGNAL"
    HEALTH_LOADING_TEXT_SIGNAL = "UB-HEALTH-LOADING-TEXT-SIGNAL"
    HEALTH_LOW_ELEMENT_DIVERSITY = "UB-HEALTH-LOW-ELEMENT-DIVERSITY"
    HEALTH_LOW_SPATIAL_COVERAGE = "UB-HEALTH-LOW-SPATIAL-COVERAGE"
    HEALTH_MANY_DISABLED_INTERACTIVE = "UB-HEALTH-MANY-DISABLED-INTERACTIVE"
    HEALTH_NO_CONTENT_ELEMENTS = "UB-HEALTH-NO-CONTENT-ELEMENTS"
    HEALTH_OFF_SCREEN_ELEMENT = "UB-HEALTH-OFF-SCREEN-ELEMENT"
    HEALTH_SPARSE_CONTENT = "UB-HEALTH-SPARSE-CONTENT"
    HEALTH_ZERO_SIZE_ELEMENT = "UB-HEALTH-ZERO-SIZE-ELEMENT"
    LOW_CONFIDENCE = "UB-LOW-CONFIDENCE"
    MULTIPLE_ELEMENTS = "UB-MULTIPLE-ELEMENTS"
    NAVIGATION_ERROR = "UB-NAVIGATION-ERROR"
    NET_ERROR = "UB-NET-ERROR"
    PAGE_LOAD_ERROR = "UB-PAGE-LOAD-ERROR"
    PARSE_ERROR = "UB-PARSE-ERROR"
    STALE_ELEMENT = "UB-STALE-ELEMENT"
    STATE_NOT_REACHED = "UB-STATE-NOT-REACHED"
    UNEXPECTED_STATE = "UB-UNEXPECTED-STATE"
    UNKNOWN_ERROR = "UB-UNKNOWN-ERROR"
    UNSUPPORTED_ACTION = "UB-UNSUPPORTED-ACTION"
    VALIDATION_ERROR = "UB-VALIDATION-ERROR"
    VLM_STRUCTURED_PARSE_FAIL = "UB-VLM-STRUCTURED-PARSE-FAIL"


UI_BRIDGE_ERROR_CODES: tuple[str, ...] = (
    "UB-ACTION-FAILED",
    "UB-ACTION-REJECTED",
    "UB-ACTION-TIMEOUT",
    "UB-AMBIGUOUS-MATCH",
    "UB-ASSERT-CONTRAST",
    "UB-ASSERT-ELEMENT-MISSING",
    "UB-ASSERT-LAYOUT",
    "UB-ASSERT-TEXT-MISMATCH",
    "UB-ASSERT-TIMEOUT",
    "UB-ASSERT-VISIBILITY",
    "UB-ELEM-BLOCKED",
    "UB-ELEM-DISABLED",
    "UB-ELEM-NOT-ENABLED",
    "UB-ELEM-NOT-FOUND",
    "UB-ELEM-NOT-INTERACTABLE",
    "UB-ELEM-NOT-VISIBLE",
    "UB-HEALTH-EMPTY-CONTENT-AREA",
    "UB-HEALTH-EMPTY-TEXT-SIGNAL",
    "UB-HEALTH-ERROR-TEXT-SIGNAL",
    "UB-HEALTH-LOADING-CLASS-SIGNAL",
    "UB-HEALTH-LOADING-TEXT-SIGNAL",
    "UB-HEALTH-LOW-ELEMENT-DIVERSITY",
    "UB-HEALTH-LOW-SPATIAL-COVERAGE",
    "UB-HEALTH-MANY-DISABLED-INTERACTIVE",
    "UB-HEALTH-NO-CONTENT-ELEMENTS",
    "UB-HEALTH-OFF-SCREEN-ELEMENT",
    "UB-HEALTH-SPARSE-CONTENT",
    "UB-HEALTH-ZERO-SIZE-ELEMENT",
    "UB-LOW-CONFIDENCE",
    "UB-MULTIPLE-ELEMENTS",
    "UB-NAVIGATION-ERROR",
    "UB-NET-ERROR",
    "UB-PAGE-LOAD-ERROR",
    "UB-PARSE-ERROR",
    "UB-STALE-ELEMENT",
    "UB-STATE-NOT-REACHED",
    "UB-UNEXPECTED-STATE",
    "UB-UNKNOWN-ERROR",
    "UB-UNSUPPORTED-ACTION",
    "UB-VALIDATION-ERROR",
    "UB-VLM-STRUCTURED-PARSE-FAIL",
)


# code -> {description, commonCauses, recoveryTemplate, category}
DIAGNOSTICS: dict[str, dict[str, Any]] = {
    "UB-ACTION-FAILED": {
        "description": "The action could not be completed.",
        "commonCauses": [
            "The element became non-interactable mid-action",
            "A transient runtime error interrupted the action",
            "The underlying handler threw",
        ],
        "recoveryTemplate": [
            {"suggestion": "Check if the element is interactable", "confidence": 0.7, "retryable": False, "priority": 1},
            {"suggestion": "Wait and retry the action", "command": "wait 1 second then retry", "confidence": 0.6, "retryable": True, "priority": 2},
        ],
        "category": "action",
    },
    "UB-ACTION-REJECTED": {
        "description": "The action was rejected before execution (e.g. by a guard, policy, or validation gate).",
        "commonCauses": [
            "A safety guard blocked the action",
            "The action is not permitted in the current state",
            "Preconditions for the action were not met",
        ],
        "recoveryTemplate": [
            {"suggestion": "Check whether the action is permitted in the current state", "confidence": 0.6, "retryable": False, "priority": 1},
            {"suggestion": "Satisfy the action's preconditions and retry", "confidence": 0.5, "retryable": True, "priority": 2},
        ],
        "category": "action",
    },
    "UB-ACTION-TIMEOUT": {
        "description": "The action timed out waiting for a condition to be met.",
        "commonCauses": [
            "The awaited condition can never be satisfied",
            "The configured timeout is too short for the operation",
            "The page stopped responding",
        ],
        "recoveryTemplate": [
            {"suggestion": "Increase the timeout duration (the wait gave up after ${waitDurationMs}ms)", "confidence": 0.8, "retryable": True, "priority": 1},
            {"suggestion": "Check if the condition '${waitCondition}' can ever be met", "confidence": 0.7, "retryable": False, "priority": 2},
            {"suggestion": "Verify the page is responding", "command": "check page status", "confidence": 0.6, "retryable": True, "priority": 3},
        ],
        "category": "action",
    },
    "UB-AMBIGUOUS-MATCH": {
        "description": "Multiple elements match with similar confidence; a single best match could not be chosen.",
        "commonCauses": [
            "Two or more elements have near-identical text",
            "The search criteria are not discriminating enough",
            "Section context was not provided",
        ],
        "recoveryTemplate": [
            {"suggestion": "Be more specific about which element you mean", "confidence": 0.9, "retryable": False, "priority": 1},
            {"suggestion": "Include the section or form name in the description", "confidence": 0.8, "retryable": False, "priority": 2},
            {"suggestion": "Use the element ID directly", "confidence": 0.7, "retryable": False, "priority": 3},
        ],
        "category": "element",
    },
    "UB-ASSERT-CONTRAST": {
        "description": "A color-contrast (accessibility) assertion failed.",
        "commonCauses": [
            "Foreground/background contrast is below the required ratio",
            "A theme change reduced contrast",
            "The element is over a low-contrast background",
        ],
        "recoveryTemplate": [
            {"suggestion": "Adjust the color tokens to meet the required contrast ratio", "confidence": 0.4, "retryable": False, "priority": 1},
        ],
        "category": "assertion",
    },
    "UB-ASSERT-ELEMENT-MISSING": {
        "description": "An assertion targeted an element that does not exist.",
        "commonCauses": [
            "The target element was never registered or rendered",
            "The element was removed before the assertion ran",
            "The selector/id is wrong",
        ],
        "recoveryTemplate": [
            {"suggestion": "Verify the element id/selector and that it is rendered before asserting", "command": "wait for element", "confidence": 0.5, "retryable": True, "priority": 1},
        ],
        "category": "assertion",
    },
    "UB-ASSERT-LAYOUT": {
        "description": "A layout/geometry assertion failed (position, size, alignment, overlap).",
        "commonCauses": [
            "The element's geometry differs from the expected layout",
            "A responsive breakpoint changed the layout",
            "The assertion ran before layout settled",
        ],
        "recoveryTemplate": [
            {"suggestion": "Wait for layout to settle and re-assert", "confidence": 0.5, "retryable": True, "priority": 1},
        ],
        "category": "assertion",
    },
    "UB-ASSERT-TEXT-MISMATCH": {
        "description": "An assertion about element text content failed (exact/contains/regex mismatch).",
        "commonCauses": [
            "The actual text differs from the expected text",
            "The text had not finished updating when asserted",
            "Whitespace or casing differences",
        ],
        "recoveryTemplate": [
            {"suggestion": "Re-read the element text and compare; relax to a contains/regex match if appropriate", "confidence": 0.5, "retryable": True, "priority": 1},
        ],
        "category": "assertion",
    },
    "UB-ASSERT-TIMEOUT": {
        "description": "An assertion timed out waiting for its condition.",
        "commonCauses": [
            "The asserted condition never became true",
            "The timeout was shorter than the time the condition needs",
            "The page stopped updating",
        ],
        "recoveryTemplate": [
            {"suggestion": "Increase the assertion timeout or verify the condition can be met", "confidence": 0.5, "retryable": True, "priority": 1},
        ],
        "category": "assertion",
    },
    "UB-ASSERT-VISIBILITY": {
        "description": "An assertion about element visibility failed.",
        "commonCauses": [
            "The element was expected visible but is hidden (or vice versa)",
            "The element had not rendered when the assertion ran",
            "An overlay changed effective visibility",
        ],
        "recoveryTemplate": [
            {"suggestion": "Wait for the element to reach the expected visibility and re-assert", "command": "wait for element", "confidence": 0.6, "retryable": True, "priority": 1},
        ],
        "category": "assertion",
    },
    "UB-ELEM-BLOCKED": {
        "description": "The element is blocked by another element such as a modal, overlay, or popup.",
        "commonCauses": [
            "A modal dialog is open over the target",
            "A toast or notification overlay intercepts pointer events",
            "A full-screen loading layer is present",
        ],
        "recoveryTemplate": [
            {"suggestion": "Close the modal or popup", "command": "click close button", "confidence": 0.9, "retryable": True, "priority": 1},
            {"suggestion": "Dismiss the overlay", "confidence": 0.8, "retryable": True, "priority": 2},
            {"suggestion": "Wait for the blocking element to disappear", "confidence": 0.6, "retryable": True, "priority": 3},
        ],
        "category": "element",
    },
    "UB-ELEM-DISABLED": {
        "description": "The element is disabled and cannot be interacted with.",
        "commonCauses": [
            "Required prerequisite fields are not yet filled",
            "A guard condition keeps the control disabled",
            "An async dependency has not resolved",
        ],
        "recoveryTemplate": [
            {"suggestion": "Fill in required fields first", "confidence": 0.8, "retryable": False, "priority": 1},
            {"suggestion": "Complete prerequisite steps", "confidence": 0.7, "retryable": False, "priority": 2},
            {"suggestion": "Wait for '${elementId}' to become enabled", "command": "wait for element to be enabled", "confidence": 0.6, "retryable": True, "priority": 3},
        ],
        "category": "element",
    },
    "UB-ELEM-NOT-ENABLED": {
        "description": "The element is present and visible but disabled, so it cannot be interacted with.",
        "commonCauses": [
            "Required form fields have not been filled",
            "A prerequisite step in a workflow is incomplete",
            "The element is intentionally disabled until an async operation completes",
        ],
        "recoveryTemplate": [
            {"suggestion": "Fill in required fields first", "confidence": 0.8, "retryable": False, "priority": 1},
            {"suggestion": "Complete prerequisite steps in the form", "confidence": 0.7, "retryable": False, "priority": 2},
            {"suggestion": "Wait for the element to become enabled", "command": "wait for element to be enabled", "confidence": 0.6, "retryable": True, "priority": 3},
        ],
        "category": "element",
    },
    "UB-ELEM-NOT-FOUND": {
        "description": "No element matching the target description or selector could be found.",
        "commonCauses": [
            "The page had not finished loading when the action ran",
            "The element is rendered only after a user interaction",
            "The description/selector does not match any element on the page",
            "The element is in a different route or tab than the active one",
        ],
        "recoveryTemplate": [
            {"suggestion": "Wait for the page to fully load, then look for '${elementId}' again", "command": "wait for page to load", "confidence": 0.7, "retryable": True, "priority": 1},
            {"suggestion": "Use a different description for the element '${elementId}'", "confidence": 0.8, "retryable": False, "priority": 2},
            {"suggestion": "Scroll the page to reveal '${elementId}'", "command": "scroll down", "confidence": 0.6, "retryable": True, "priority": 3},
        ],
        "category": "element",
    },
    "UB-ELEM-NOT-INTERACTABLE": {
        "description": "The element is visible and enabled but cannot receive the interaction (e.g. covered, animating, or pointer-events:none).",
        "commonCauses": [
            "A modal or popup is overlaying the element",
            "A CSS animation or transition is in progress",
            "The element is partially outside the viewport",
            "pointer-events:none is set on the element or an ancestor",
        ],
        "recoveryTemplate": [
            {"suggestion": "Close any modal or popup blocking the element", "command": "click close button", "confidence": 0.9, "retryable": True, "priority": 1},
            {"suggestion": "Scroll the element into the viewport", "command": "scroll to element", "confidence": 0.8, "retryable": True, "priority": 2},
            {"suggestion": "Wait for animations to complete", "confidence": 0.7, "retryable": True, "priority": 3},
        ],
        "category": "element",
    },
    "UB-ELEM-NOT-VISIBLE": {
        "description": "The element exists in the DOM but is not currently visible.",
        "commonCauses": [
            "The element is scrolled out of the viewport",
            "A loading overlay or modal is covering it",
            "A parent has display:none or visibility:hidden",
            "The element has zero size or no layout box",
        ],
        "recoveryTemplate": [
            {"suggestion": "Scroll to make '${elementId}' visible", "command": "scroll to element", "confidence": 0.9, "retryable": True, "priority": 1},
            {"suggestion": "Close any blocking modals or popups", "command": "click close button", "confidence": 0.8, "retryable": True, "priority": 2},
            {"suggestion": "Wait for any loading overlays to disappear", "command": "wait for loading", "confidence": 0.7, "retryable": True, "priority": 3},
        ],
        "category": "element",
    },
    "UB-HEALTH-EMPTY-CONTENT-AREA": {
        "description": "Page health: the main content area is nearly empty while the sidebar/left region has content.",
        "commonCauses": [
            "The content panel failed to render",
            "A data fetch for the main view errored",
            "A routing issue left the content region blank",
        ],
        "recoveryTemplate": [
            {"suggestion": "Reload the view and re-run the health check", "command": "refresh page", "confidence": 0.6, "retryable": True, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-EMPTY-TEXT-SIGNAL": {
        "description": "Page health: empty-state text was detected (e.g. \"no results\", \"nothing here\").",
        "commonCauses": [
            "A data set returned no items",
            "A filter excluded all results",
            "The expected data failed to load",
        ],
        "recoveryTemplate": [
            {"suggestion": "Verify the data source and filters; re-run the health check after data loads", "confidence": 0.4, "retryable": False, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-ERROR-TEXT-SIGNAL": {
        "description": "Page health: error-indicating text was detected on the page.",
        "commonCauses": [
            "An application error was rendered to the user",
            "A failed request surfaced an error banner",
            "An exception boundary rendered a fallback",
        ],
        "recoveryTemplate": [
            {"suggestion": "Inspect the error message and address the underlying failure before retrying", "confidence": 0.5, "retryable": False, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-LOADING-CLASS-SIGNAL": {
        "description": "Page health: a loading/skeleton/spinner CSS class was detected on a visible element.",
        "commonCauses": [
            "A skeleton or spinner is still showing",
            "An async region has not resolved",
        ],
        "recoveryTemplate": [
            {"suggestion": "Wait for the loading indicator to clear and re-run the health check", "command": "wait for loading", "confidence": 0.6, "retryable": True, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-LOADING-TEXT-SIGNAL": {
        "description": "Page health: loading-indicating text was detected, suggesting the page is not settled.",
        "commonCauses": [
            "An async load is still in progress",
            "The page is stuck in a loading state",
        ],
        "recoveryTemplate": [
            {"suggestion": "Wait for loading to complete and re-run the health check", "command": "wait for loading", "confidence": 0.6, "retryable": True, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-LOW-ELEMENT-DIVERSITY": {
        "description": "Page health: all visible elements are navigation-type, suggesting the content body is missing.",
        "commonCauses": [
            "Only chrome/navigation rendered; the body did not",
            "Content failed to load behind the navigation shell",
        ],
        "recoveryTemplate": [
            {"suggestion": "Reload the page and re-run the health check", "command": "refresh page", "confidence": 0.5, "retryable": True, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-LOW-SPATIAL-COVERAGE": {
        "description": "Page health: rendered elements occupy a critically/abnormally small fraction of the viewport.",
        "commonCauses": [
            "The page is still loading content",
            "A render error left most of the page blank",
            "The main content failed to mount",
        ],
        "recoveryTemplate": [
            {"suggestion": "Wait for the page to finish loading and re-run the health check", "command": "wait for page to load", "confidence": 0.6, "retryable": True, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-MANY-DISABLED-INTERACTIVE": {
        "description": "Page health: over half of interactive elements are disabled.",
        "commonCauses": [
            "The page is gated behind an unmet precondition",
            "A loading state disabled most controls",
            "The user lacks permission for most actions",
        ],
        "recoveryTemplate": [
            {"suggestion": "Satisfy the precondition that enables the controls, then re-run the health check", "confidence": 0.4, "retryable": False, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-NO-CONTENT-ELEMENTS": {
        "description": "Page health: no elements were found in the content region.",
        "commonCauses": [
            "The content view did not mount",
            "An exception prevented content rendering",
            "The page is stuck before content load",
        ],
        "recoveryTemplate": [
            {"suggestion": "Reload the page and re-run the health check", "command": "refresh page", "confidence": 0.6, "retryable": True, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-OFF-SCREEN-ELEMENT": {
        "description": "Page health: a visible element is positioned entirely off-screen.",
        "commonCauses": [
            "A negative-offset or transform pushed the element out of view",
            "A layout bug positioned the element outside the viewport",
        ],
        "recoveryTemplate": [
            {"suggestion": "Inspect the element's positioning/CSS; this typically indicates a layout defect", "confidence": 0.3, "retryable": False, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-SPARSE-CONTENT": {
        "description": "Page health: the content region has very few elements.",
        "commonCauses": [
            "Content is only partially rendered",
            "A list/grid returned few or no items",
            "The page is mid-load",
        ],
        "recoveryTemplate": [
            {"suggestion": "Wait for content to finish loading and re-run the health check", "command": "wait for loading", "confidence": 0.5, "retryable": True, "priority": 1},
        ],
        "category": "system",
    },
    "UB-HEALTH-ZERO-SIZE-ELEMENT": {
        "description": "Page health: a visible element has zero width or height.",
        "commonCauses": [
            "A CSS layout bug collapsed the element",
            "Missing content gave the element no intrinsic size",
            "A fl/grid sizing rule produced a zero box",
        ],
        "recoveryTemplate": [
            {"suggestion": "Inspect the element's layout/CSS; this typically indicates a rendering defect", "confidence": 0.3, "retryable": False, "priority": 1},
        ],
        "category": "system",
    },
    "UB-LOW-CONFIDENCE": {
        "description": "The best matching element has confidence below the acceptance threshold.",
        "commonCauses": [
            "The description does not closely match any element's text",
            "The confidence threshold is set higher than the actual best match",
            "The element label differs from the human-expected wording",
        ],
        "recoveryTemplate": [
            {"suggestion": "Use the exact text shown on the element", "confidence": 0.9, "retryable": False, "priority": 1},
            {"suggestion": "Try a different description that more closely matches the element", "confidence": 0.8, "retryable": False, "priority": 2},
            {"suggestion": "Lower the confidence threshold if the match is correct", "confidence": 0.7, "retryable": True, "priority": 3},
        ],
        "category": "element",
    },
    "UB-MULTIPLE-ELEMENTS": {
        "description": "Multiple elements match the description; the target is ambiguous.",
        "commonCauses": [
            "The description is too generic",
            "Repeated list/grid items share the same label",
            "Several controls have identical accessible names",
        ],
        "recoveryTemplate": [
            {"suggestion": "Use a more specific description", "confidence": 0.9, "retryable": False, "priority": 1},
            {"suggestion": "Include the element position (first, second, etc.)", "confidence": 0.8, "retryable": False, "priority": 2},
            {"suggestion": "Use the element ID directly", "confidence": 0.7, "retryable": False, "priority": 3},
        ],
        "category": "element",
    },
    "UB-NAVIGATION-ERROR": {
        "description": "Navigation to the target page failed.",
        "commonCauses": [
            "The target URL is incorrect or unreachable",
            "A navigation guard blocked the route",
            "The route does not exist",
        ],
        "recoveryTemplate": [
            {"suggestion": "Try the navigation again", "confidence": 0.7, "retryable": True, "priority": 1},
            {"suggestion": "Check if the URL is correct", "confidence": 0.6, "retryable": False, "priority": 2},
        ],
        "category": "network",
    },
    "UB-NET-ERROR": {
        "description": "A network error occurred while performing the action or loading data.",
        "commonCauses": [
            "The backing request failed or timed out",
            "Connectivity was lost",
            "A CORS or proxy error blocked the request",
        ],
        "recoveryTemplate": [
            {"suggestion": "Retry the action once connectivity is restored", "confidence": 0.6, "retryable": True, "priority": 1},
            {"suggestion": "Check network connectivity", "confidence": 0.5, "retryable": False, "priority": 2},
        ],
        "category": "network",
    },
    "UB-PAGE-LOAD-ERROR": {
        "description": "The page failed to load correctly.",
        "commonCauses": [
            "A critical resource failed to load",
            "The server returned an error response",
            "Network connectivity was interrupted during load",
        ],
        "recoveryTemplate": [
            {"suggestion": "Refresh the page", "command": "refresh page", "confidence": 0.8, "retryable": True, "priority": 1},
            {"suggestion": "Check network connectivity", "confidence": 0.6, "retryable": False, "priority": 2},
        ],
        "category": "network",
    },
    "UB-PARSE-ERROR": {
        "description": "Could not parse the natural language instruction.",
        "commonCauses": [
            "The instruction is too complex or ambiguous to parse",
            "The instruction does not reference a recognizable action",
            "The instruction format is unsupported",
        ],
        "recoveryTemplate": [
            {"suggestion": "Use a simpler instruction format like \"click Submit button\"", "confidence": 0.8, "retryable": False, "priority": 1},
            {"suggestion": "Use specific element names visible on the page", "confidence": 0.7, "retryable": False, "priority": 2},
        ],
        "category": "system",
    },
    "UB-STALE-ELEMENT": {
        "description": "The element reference is no longer attached to the DOM.",
        "commonCauses": [
            "The component unmounted between discovery and action",
            "A re-render replaced the element node",
            "The element was detached by a parent update",
        ],
        "recoveryTemplate": [
            {"suggestion": "Re-find '${elementId}'", "confidence": 0.9, "retryable": True, "priority": 1},
            {"suggestion": "Wait for page to stabilize", "command": "wait 1 second", "confidence": 0.7, "retryable": True, "priority": 2},
        ],
        "category": "element",
    },
    "UB-STATE-NOT-REACHED": {
        "description": "The expected post-action state was not reached.",
        "commonCauses": [
            "The action did not produce the expected state transition",
            "An async side-effect has not completed yet",
            "The expected state assertion is incorrect",
        ],
        "recoveryTemplate": [
            {"suggestion": "Wait for state to stabilize and re-check", "command": "wait 2 seconds", "confidence": 0.6, "retryable": True, "priority": 1},
            {"suggestion": "Verify the expected state condition is correct", "confidence": 0.5, "retryable": False, "priority": 2},
        ],
        "category": "system",
    },
    "UB-UNEXPECTED-STATE": {
        "description": "The element or page is in an unexpected state.",
        "commonCauses": [
            "The page state drifted from what the workflow assumed",
            "A concurrent update changed the state",
            "Stale state was used for the decision",
        ],
        "recoveryTemplate": [
            {"suggestion": "Refresh the page state", "command": "refresh", "confidence": 0.7, "retryable": True, "priority": 1},
            {"suggestion": "Wait for state to stabilize", "command": "wait 2 seconds", "confidence": 0.6, "retryable": True, "priority": 2},
        ],
        "category": "system",
    },
    "UB-UNKNOWN-ERROR": {
        "description": "An unknown or uncategorized error occurred.",
        "commonCauses": [
            "An unexpected runtime exception with no specific code",
            "An error path that has not yet been mapped to a stable code",
        ],
        "recoveryTemplate": [
            {"suggestion": "Try a different approach or check the page state", "confidence": 0.5, "retryable": False, "priority": 1},
        ],
        "category": "system",
    },
    "UB-UNSUPPORTED-ACTION": {
        "description": "The requested action type is not supported for this element or surface.",
        "commonCauses": [
            "The action verb is not implemented for the element type",
            "A composite action needs to be broken into primitives",
        ],
        "recoveryTemplate": [
            {"suggestion": "Use a different action type", "confidence": 0.9, "retryable": False, "priority": 1},
            {"suggestion": "Break down into simpler actions", "confidence": 0.7, "retryable": False, "priority": 2},
        ],
        "category": "action",
    },
    "UB-VALIDATION-ERROR": {
        "description": "The parsed action failed validation.",
        "commonCauses": [
            "Required parameters for the action are missing",
            "A parameter value is out of range or the wrong type",
            "The instruction format is invalid",
        ],
        "recoveryTemplate": [
            {"suggestion": "Provide required parameters for the action", "confidence": 0.9, "retryable": False, "priority": 1},
            {"suggestion": "Check the instruction format", "confidence": 0.7, "retryable": False, "priority": 2},
        ],
        "category": "system",
    },
    "UB-VLM-STRUCTURED-PARSE-FAIL": {
        "description": "The VLM Describe response could not be parsed into the closed structured schema; the prose-only response was returned with structured=null.",
        "commonCauses": [
            "The model returned malformed or non-JSON output in JSON mode",
            "The structured payload did not validate against the schema",
            "Model-specific JSON-mode unreliability",
        ],
        "recoveryTemplate": [
            {"suggestion": "Fall back to the prose description; retry the describe call once", "confidence": 0.4, "retryable": True, "priority": 1},
        ],
        "category": "system",
    },
}
